const cryptos=[
    {
        Id:1,
        Nombre:"BTC",
        Descripcion:"Bitcoin",
        PrecioEnUSD:20000,
        Logo:"RutaImg"        
    },
    {
        Id:2,
        Nombre:"ETH",
        Descripcion:"Ehtereum",
        PrecioEnUSD:1700,
        Logo:"RutaImg"
    },
    {
        Id:3,
        Nombre:"BNB",
        Descripcion:"BNB",
        PrecioEnUSD:320,
        Logo:"RutaImg"
    },
    {
        Id:1,
        Nombre:"ADA",
        Descripcion:"Cardano",
        PrecioEnUSD:0.355,
        Logo:"RutaImg"
    }
]